/*
 ############################################################################
 # FiledataField	: MsCostCenterCtgyInfoUploadExcelPopup.tsx
 # Description		: 거래처기준정보 > 마감기준정보 > 사업부상세조직분류 엑셀 업로드 팝업
 # Author			: Generated by Assistant
 # Since			: 25.12.09
 ############################################################################
*/

// lib
import AUIGrid from '@/lib/AUIGrid/AUIGridReactCanal';
import { Button } from 'antd';

// component
import ButtonWrap from '@/assets/styled/ButtonWrap/ButtonWrap';
import PopupMenuTitle from '@/components/common/custom/PopupMenuTitle';
import GridTopBtn from '@/components/common/GridTopBtn';

// css
import AGrid from '@/assets/styled/AGrid/AGrid';

// api
import {
	apiPostSaveCostCenterCtgyExcelList,
	apiValidateCostCenterCtgyExcelList,
} from '@/api/ms/apiMsCostCenterCtgyInfo';

// util
import fileUtil from '@/util/fileUtils';

// type
import { GridBtnPropsType } from '@/types/common';

interface PropsType {
	close?: () => void;
}

const MsCostCenterCtgyInfoUploadExcelPopup = (props: PropsType) => {
	const { close } = props;
	const { t } = useTranslation();

	const gridRef = useRef<any>(null);
	const excelUploadFileRef = useRef<any>(null);

	const gridCol = [
		{
			// 엑셀 업로드시 날짜 dataType이 날짜를 보정하여 string으로 수정
			dataField: 'applyYm',
			headerText: t('lbl.APPLY_MONTH'),
			dataType: 'string',
			required: true,
		},
		{
			dataField: 'custkey',
			headerText: t('lbl.CUST_CODE'),
			dataType: 'code',
			required: true,
		},
		// {
		// 	dataField: 'deptCd',
		// 	headerText: t('lbl.DEPT_CD'),
		// 	dataType: 'code',
		// 	required: true,
		// },
		{
			dataField: 'deptNm',
			headerText: t('lbl.DEPT_NM'),
			dataType: 'string',
		},
		{
			dataField: 'hierachyNm',
			headerText: '경로/업종',
			dataType: 'string',
		},
		{
			dataField: 'lclNm',
			headerText: t('lbl.CLASS_BIG'),
			dataType: 'string',
		},
		{
			dataField: 'mclNm',
			headerText: t('lbl.CLASS_MIDDLE'),
			dataType: 'string',
		},
		{
			dataField: 'sclNm',
			headerText: t('lbl.CLASS_SMALL'),
			dataType: 'string',
		},
	];

	const gridProps = {
		editable: false,
		showRowCheckColumn: true,
		enableFilter: true,
		showCustomRowCheckColumn: true,
	};

	// applyYm: YYYY-MM 형식을 YYYYMM 형식으로 변환
	const formatApplyYm = (value: string) => {
		// 하이픈을 포함하고 있지 않다면 그대로 반환
		if (!value.includes('-')) {
			return value;
		}
		return `${value.split('-')[0]}${value.split('-')[1]}`;
	};

	// delay to ensure grid internal validation is ready
	const validateGridDataWithDelay = () => {
		return new Promise<boolean>(resolve => {
			setTimeout(() => {
				const isValid = gridRef.current.validateRequiredGridData();
				// BOOLEAN 캐스팅
				resolve(!!isValid);
			}, 50);
		});
	};

	const onFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		gridRef.current.changeColumnLayout(gridCol);
		fileUtil.excelImport(e, 0, gridBtn.tGridRef, 1, validateExcelList);
	};

	const validateExcelList = async () => {
		const preParams = gridRef.current.getGridData();

		// applyYm 포맷팅
		const params = preParams.map((item: any) => ({
			...item,
			applyYm: item.applyYm ? formatApplyYm(item.applyYm) : null,
		}));

		if (!params || params.length < 1) {
			showMessage({ content: t('msg.MSG_COM_VAL_020'), modalType: 'info' });
			return;
		}

		const isValid = await validateGridDataWithDelay();
		if (!isValid) return;

		// PK validation: custkey + applyYm + deptCd
		if (!gridRef.current.validatePKGridData(['custkey', 'applyYm', 'deptCd'])) {
			return;
		}

		apiValidateCostCenterCtgyExcelList(params).then((res: any) => {
			const checkColumn = [
				{ dataField: 'processYn', headerText: '체크결과' },
				{ dataField: 'processMsg', headerText: '체크메시지' },
			];
			gridRef.current.addColumn(checkColumn, 1);

			const rowsToUpdate = res.data.data || [];
			const updateData: any[] = [];
			const updateIndex: any[] = [];

			const gridRows = gridRef.current.getGridData();
			rowsToUpdate.forEach((row: any) => {
				const foundIndex = gridRows.findIndex(
					(g: any) => g.custkey == row.custkey && formatApplyYm(g.applyYm) == row.applyYm && g.deptCd == row.deptCd,
				);
				if (foundIndex >= 0) {
					const rowIndex = gridRef.current.getRowIndexesByValue('_$uid', [gridRows[foundIndex]._$uid]);
					if (rowIndex !== undefined) {
						let processMsg = '정상';
						let processYn = 'Y';
						if (row.custkeyChk === 'N') {
							processMsg = '고객코드가 존재하지 않습니다.';
							processYn = 'N';
						} else if (row.deptCdChk === 'N') {
							processMsg = '업무부코드가 존재하지 않습니다.';
							processYn = 'N';
						} else if (row.applyYmChk === 'N') {
							processMsg = '적용월 형식이 올바르지 않습니다.';
							processYn = 'N';
						}

						let rowStatus = 'I';
						if (row.updateYn === 'Y') {
							rowStatus = 'U';
						}

						updateData.push({ processYn, processMsg, rowStatus });
						updateIndex.push(rowIndex);
					}
				}
			});

			if (updateData.length > 0) {
				gridRef.current.updateRows(updateData, updateIndex);
			}

			// uncheck rows with failures
			const uncheckedItems = gridRef.current.getGridData().filter((it: any) => it.processYn === 'N');
			const uncheckedIds = uncheckedItems.map((it: any) => it._$uid);
			gridRef.current.addUncheckedRowsByIdsBefore(uncheckedIds);
		});
	};

	const saveExcelList = () => {
		const preParams = gridRef.current.getGridData();

		// applyYm 포맷팅
		const params = preParams.map((item: any) => ({
			...item,
			applyYm: item.applyYm ? formatApplyYm(item.applyYm) : null,
		}));

		const isProcessYN = params.some((it: any) => it.processYn !== 'Y');
		if (isProcessYN) {
			showMessage({
				content: '유효성 검증이 완료되지 않은 데이터가 포함되어 있습니다.\n확인 후 다시 시도해주세요.',
				modalType: 'info',
			});
			return;
		}

		const updateLength = params.filter((it: any) => it.rowStatus === 'U').length;
		const insertLength = params.filter((it: any) => it.rowStatus === 'I').length;
		const messageWithRowStatusCount = `${t(
			'msg.confirmSave',
		)}\n신규 : ${insertLength}건\n수정 : ${updateLength}건\n삭제 : 0건`;

		showConfirm(null, messageWithRowStatusCount, () => {
			apiPostSaveCostCenterCtgyExcelList(params).then(() => {
				showMessage({
					content: t('msg.MSG_COM_SUC_003'),
					modalType: 'info',
					onOk: () => close && close(),
				});
			});
		});
	};

	const gridBtn: GridBtnPropsType = {
		tGridRef: gridRef,
		btnArr: [
			// { btnType: 'excelForm' },
			{
				btnType: 'excelSelect',
				isActionEvent: false,
				callBackFn: () => excelUploadFileRef.current.click(),
			},
			{ btnType: 'save', callBackFn: saveExcelList },
		],
	};

	/**
	 * 엑셀 양식 다운로드
	 * 로케이션 일괄업로드만 공통 기능을 사용하지 않고 버튼으로 추가(별도양식)
	 */
	const onExcelDownload = () => {
		const params = {
			dirType: 'excelTemplate',
			attchFileNm: '출고_데이터_결산_마스터.xlsx',
		};

		fileUtil.downloadFile(params);
	};

	return (
		<>
			<PopupMenuTitle name="사업부상세조직분류 일괄업로드" showButtons={false} />
			<AGrid>
				<GridTopBtn gridBtn={gridBtn} gridTitle={' '}>
					{/* "양식 다운로드"를 gridBtn으로 넘기지 않고 버튼으로 추가 */}
					<Button onClick={onExcelDownload}>양식다운로드</Button>
				</GridTopBtn>
				<AUIGrid ref={gridRef} columnLayout={gridCol} gridProps={gridProps} />
			</AGrid>

			<ButtonWrap data-props="single">
				<Button onClick={close}>{t('lbl.BTN_CANCEL') || '취소'}</Button>
			</ButtonWrap>

			{/* hidden input for excel selection */}
			<input
				ref={excelUploadFileRef}
				id="excelUploadInput"
				type="file"
				onChange={onFileChange}
				onClick={(e: any) => {
					e.target.value = null;
				}}
				style={{ display: 'none' }}
			/>
		</>
	);
};

export default MsCostCenterCtgyInfoUploadExcelPopup;
