server {
  listen 8087;
  client_max_body_size 5M;

  #access_log /logs/access.log;
  #error_log /logs/error.log;

  # 선도개발 서버 static 파일 임시 설정
  location /files/ {
    alias /app/cf-apiserver/upload/;
  }

  location / {
    alias /usr/share/nginx/html/;
    try_files $uri $uri/ /index.html;
  }
}
